PATHS:
  # This file is used to extract the locations (and other metadata) of the discovered GRGs
  GIANTS_CATALOG_FILEPATH: "/home/penchev/strw_lofar_data_utils/data/discovered_giants_catalogue.csv"

  # This file is used to link components to sources for the annotation procedure
  COMPONENT_CATALOGUE_FILEPATH: "/net/vdesk/data2/penchev/project_data/data/combined_cat/combined-components-v0.8.fits"

  # Where to save the generated dataset
  SAVE_DIR: "/net/vdesk/data2/penchev/project_data/inspect-pipeline/"

CUTOUT_PARAMS:
  CUTOUT_SIZE: 425 # pixels - this gives us 300 pixels after rotation of 45 degrees
  CROP_SIZE: 300 # pixels - final size after rotation and cropping
  RMS: 0.0001
  NR_SIGMAS: 3 # Number of sigmas above RMS to consider for source segmentation

AUGMENTATION:
  # to keep consistency with previous work by Moesterd et al.
  # It is possible to use 'asinh_stretch' as well
  STRETCH_TYPE: "sqrt_stretch"

  # Angles in degrees to rotate the cutouts for data augmentation. 0 means no rotation.
  ROTATION_ANGLES: [0, 45, 90, 135, 180, 225, 270, 315]
  
  # Limits the number of islands to precompute per cutout.
  # This limits the number of precomputed proposals we get for the RCNN model.
  # The number of proposals is equal to 2^n - 1, where n is the number of islands.
  MAX_PRECOMPUTED_ISLANDS: 10

ANNOTATIONS:
  # "rle" or "polygon" - rle is better for astro images.
  # Polygons approximate shapes while RLE has exact pixel-level accuracy.
  SEGMENTATION_MODE: "rle" 
